version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysched-mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root #cambiar a $MYSQL_ROOT_PASSWORD en .env por ejemplo
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] #cambiar a $MYSQL_ROOT_PASSWORD en .env por ejemplo
      interval: 5s
      timeout: 15s
      retries: 10

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      bash -c "sleep 10 
      && php artisan migrate:fresh --force
      && php artisan db:seed --force"
    restart: on-failure
    networks:
      - laravel_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mysched-api
    ports:
      - "${API_PORT}:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel_network

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mysched-front
    ports:
      - "${HTTPD_PORT}:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    networks:
      - laravel_network

volumes:
  mysqldata:

networks:
  laravel_network:
    driver: bridge