version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysched-mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - laravel_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mysched-api
    ports:
      - "${API_PORT}:80"
    depends_on:
      - mysql
    networks:
      - laravel_network

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mysched-front
    ports:
      - "${HTTPD_PORT}:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    networks:
      - laravel_network

volumes:
  mysqldata:

networks:
  laravel_network:
    driver: bridge